@host = http://127.0.0.1:3005

OPTIONS {{host}}/

###

GET {{host}}/posts

###

POST {{host}}/post
Content-Type: application/json

{
    "name": "Albert",
    "tags": ["測試", "程式"],
    "type": "person",
    "content": "  Test..."
}

###

DELETE {{host}}/posts

###

DELETE {{host}}/post/6639e3cdf7d5514d9fc2511b

###

PATCH {{host}}/post/6639e3c9f7d5514d9fc25119
Content-Type: application/json

{
    "content": "updated content..."
}
