@host = http://127.0.0.1:3005

OPTIONS {{host}}/

###

GET {{host}}/posts

###

POST {{host}}/posts
Content-Type: application/json

{
    "name": "Zoe",
    "tags": ["測試", "程式"],
    "type": "person",
    "content": "  Test...   "
}

###

DELETE {{host}}/posts/663462769630b810d32227ce

###

PATCH {{host}}/posts/66363c1e0ac79d4f35923ae4
Content-Type: application/json

{
    "content": "updated content..."
}
